### ISSUE TITLE
name

### ISSUE THREAD

**Issue by calvix** [exmonitor/exmonitor#19]
lets discuss possible name ideas here:

**Comment by calvix** [comment]
nice name generator/combinator is here https://www.nameacronym.net/name-combiner.aspx

**Comment by calvix** [comment]
few ideas that  got spilled by the generator:
```
alerg
alertool
alertoing
monitool
montool
monitee
monitoe
monitorthat
teehat
thatmonitoring
thatalert
checkalert
```

**Comment by hrnjan** [comment]
monitoe.com is available
or we could register alertee.eu domain -> monitee.com (which I like) is also taken.

**Comment by calvix** [comment]
```
alertee.net
monitee.net   ( enjoy some tea while we monitor your servers !)
``` 
is also available

**Comment by calvix** [comment]
`alertea` - > `alertea.com`
